# Generated by Django 2.1.7 on 2019-02-28 20:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=264),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sent_receipts',
            name='transaction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sent_receipts_files'),
        ),
        migrations.AlterField(
            model_name='sent_receipts_files',
            name='transaction_id',
            field=models.CharField(max_length=264),
        ),
    ]
