# Generated by Django 2.1.7 on 2019-03-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190301_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_SAP', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='sent_receipts',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='sent_receipts',
            name='vendor_id',
        ),
        migrations.DeleteModel(
            name='Sent_receipts',
        ),
        migrations.DeleteModel(
            name='Sent_receipts_files',
        ),
        migrations.DeleteModel(
            name='Vendors',
        ),
    ]
