# Generated by Django 2.1.7 on 2019-03-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190301_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapfile',
            name='desc',
            field=models.CharField(default='SAP file', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sapfile',
            name='sample_SAP',
            field=models.FileField(upload_to='SAP/'),
        ),
    ]
