# Generated by Django 2.1.7 on 2019-03-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card_Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Transaction_ID', models.CharField(max_length=15)),
                ('Vendor_ID', models.CharField(max_length=15)),
                ('Vendor_Name', models.CharField(max_length=264)),
                ('Vendor_email', models.EmailField(max_length=254)),
                ('Amount', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cheque_Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Transaction_ID', models.CharField(max_length=15)),
                ('Vendor_ID', models.CharField(max_length=15)),
                ('Vendor_Name', models.CharField(max_length=264)),
                ('Vendor_email', models.EmailField(max_length=254)),
                ('Amount', models.CharField(max_length=20)),
            ],
        ),
    ]
