# Generated by Django 2.1.7 on 2019-03-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_receipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_transactions',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cheque_transactions',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
