# Generated by Django 2.1.7 on 2019-03-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_receipt', '0002_auto_20190302_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_transactions',
            name='unique_key',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cheque_transactions',
            name='unique_key',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
