# Generated by Django 2.1.7 on 2019-03-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_receipt', '0003_auto_20190303_0407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card_transactions',
            old_name='Amount',
            new_name='Discount',
        ),
        migrations.RenameField(
            model_name='cheque_transactions',
            old_name='Amount',
            new_name='Discount',
        ),
        migrations.AddField(
            model_name='card_transactions',
            name='Discount_per',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card_transactions',
            name='Products',
            field=models.CharField(default=0, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card_transactions',
            name='Tax_amount',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card_transactions',
            name='Tax_per',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card_transactions',
            name='Total_Amount',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cheque_transactions',
            name='Discount_per',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cheque_transactions',
            name='Products',
            field=models.CharField(default=0, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cheque_transactions',
            name='Tax_amount',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cheque_transactions',
            name='Tax_per',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cheque_transactions',
            name='Total_Amount',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
